language: generic # Dont want travis to set anything clang/gcc related

os: linux
dist: jammy 

env:
  - DEFCONFIG=exynos9810-crownlte_defconfig
  - DEFCONFIG=exynos9810-starlte_defconfig
  - DEFCONFIG=exynos9810-star2lte_defconfig


before_install:
  # Remove any old clang versions, which interfere
  - sudo apt-get update -y
  - sudo apt remove clang-*
  - sudo rm -rf  /usr/local/clang-*

  # Install llvm 14
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 14 
  
  # Link llvm 14 to the defaults
  - sudo ln -s /usr/bin/clang-14 /usr/bin/clang
  - sudo ln -s /usr/bin/ld.lld-14 /usr/bin/ld.lld
  - export PATH=/usr/bin/:$PATH


install:
  - sudo apt install gcc-aarch64-linux-gnu -y
  - sudo apt install gcc-arm-linux-gnueabi

before_script:
  - mkdir release_out/

script:
  - export ARCH=arm64 
  - export CC=clang
  - export LD=ld.lld
  - export LLVM=1
  - export LLVM_IAS=1
  - export CLANG_TRIPLE=aarch64-linux-gnu-
  - export CROSS_COMPILE=aarch64-linux-gnu-
  - export CROSS_COMPILE_ARM32="arm-linux-gnueabi-"

  - clang --version

  - make O=out "-j$(nproc)" $DEFCONFIG  2>&1 | tee release_out/log_make.txt
  - make O=out "-j$(nproc)" 2>&1 | tee release_out/log_make.txt

after_script:
  - tar czf release_out/kernel_out.tar.gz out/

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "eshark"
  - git config --local user.email "admin@eshark.tech"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  # opt in to dpl v2
  edge: true 

  # Dont delete the files we want to upload :/
  cleanup: false

  # Release on everything
  on:
    all_branches: true
  
  # The files to upload:
  file_glob: true
  file: release_out/*
  
  # Upload to github releases
  provider: releases
  token:
    secure: MPT+Rk598MbRkumIAnEK2RxcJRNVXtaKVOVSSgIXwetHhJyp+zGa9Yv0OEIrxRuSlikMsLd7hCW7iHrdXfOlb1+Tmg8611/itEXKFcYK1vOQ0jvdLmKdzEHFkZDDaGexloBfiborm51R1GAlE0e0uO3EvSwsKhvEFt7Xqzesw7AYQ/9gUVlIhIC3pRuvu+5ah6PIC1OxeXReJN3mbl3jKXsd+GS5413m4uXRKdM85Bp73QguM83OfvCLr34+mKv6sTc9Z/ibnhq9vunVH7rcfFG/YktnbIHKZaMyO8wECGgBc5nGPayScN0VHFvL1W4ZrvgjVgtkrFCdSSGRSeBmrj8YvOFdRYETPOCTeNmAfMydOBP+lW7OEjikbV8wVrAVEoBu12MpomnSP2gaYr6uEReGi4Z3a+w6WKoU0RQYDad3C61Pq0vPpU9q4N42YA4Lw1vbxi3DuMmD9nYu2G5rerfMPiyNYBtmWTzHpxo0EDIRlpbE9vuHPoovNqAN3YRcBWDoyxhgnVKeqSfZtm5OPBLlt8qJyOCbsv4VcuJ1Hu+uJu4k29MNuIuBklv5y+Ls7zu6QmdPZr9V5ak/pqxVvPzMQoDFRK6uI3mdxi3mkcpggz7a00zzgvoJl1R90lss8xpm5/rbGdMtd1boiecWcjuZyvKJQa7r3kajKuywH8M=

cache:
  apt: true