language: generic # Dont want travis to set anything clang/gcc related

os: linux
dist: jammy 

env:
  - DEFCONFIG=exynos9810-crownlte_defconfig
  - DEFCONFIG=exynos9810-starlte_defconfig
  - DEFCONFIG=exynos9810-star2lte_defconfig


before_install:
  - sudo apt-get update -y
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" # Install llvm

install:
  - sudo apt install gcc-aarch64-linux-gnu -y
  - sudo apt install gcc-arm-none-eabi

script:
  - export ARCH=arm64 
  - export CC=clang
  - export CROSS_COMPILE=aarch64-linux-gnu-
  - export CROSS_COMPILE_ARM32="arm-none-eabi-"

  - make "-j$(nproc)" $DEFCONFIG
  - make "-j$(nproc)"

cache:
  apt: true
