language: generic # Dont want travis to set anything clang/gcc related

os: linux
dist: jammy 

env:
  - DEFCONFIG=exynos9810-crownlte_defconfig
  - DEFCONFIG=exynos9810-starlte_defconfig
  - DEFCONFIG=exynos9810-star2lte_defconfig


before_install:
  - sudo apt-get update -y
  - sudo apt remove clang-*
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" # Install llvm
  - sudo ln -s /usr/bin/clang-18 /usr/bin/clang
  - export PATH=/usr/bin/:$PATH


install:
  - sudo apt install gcc-aarch64-linux-gnu -y
  - sudo apt install gcc-arm-linux-eabi

script:
  - export O=out
  - export ARCH=arm64 
  - export CC=clang
  - export LD=ld.lld
  - export LLVM=1
  - export LLVM_IAS=1
  - export CLANG_TRIPLE=aarch64-linux-gnu-
  - export CROSS_COMPILE=aarch64-linux-gnu-
  - export CROSS_COMPILE_ARM32="arm-linux-eabi-"

  - clang --version

  - make "-j$(nproc)" $DEFCONFIG
  - make "-j$(nproc)"

cache:
  apt: true

