language: generic # Dont want travis to set anything clang/gcc related

os: linux
dist: jammy 

env:
  - DEFCONFIG=exynos9810-crownlte_defconfig
  - DEFCONFIG=exynos9810-starlte_defconfig
  - DEFCONFIG=exynos9810-star2lte_defconfig


before_install:
  - sudo apt-get update -y
  - sudo apt remove clang-*
  - sudo rm -rf  /usr/local/clang-*

  # Install llvm 14
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 14 
  
  - sudo ln -s /usr/bin/clang-14 /usr/bin/clang
  - sudo ln -s /usr/bin/ld.lld-14 /usr/bin/ld.lld
  - export PATH=/usr/bin/:$PATH


install:
  - sudo apt install gcc-aarch64-linux-gnu -y
  - sudo apt install gcc-arm-linux-gnueabi

script:
  - export O=out
  - export ARCH=arm64 
  - export CC=clang
  - export LD=ld.lld
  - export LLVM=1
  - export LLVM_IAS=1
  - export CLANG_TRIPLE=aarch64-linux-gnu-
  - export CROSS_COMPILE=aarch64-linux-gnu-
  - export CROSS_COMPILE_ARM32="arm-linux-gnueabi-"

  - clang --version

  - make "-j$(nproc)" $DEFCONFIG
  - make "-j$(nproc)"

cache:
  apt: true

