name: Kernel Build
run-name: Kernel Build caused by ${{github.event_name}} - ${{github.actor}} 

on: [push]

jobs:
  KernelBuild:
    runs-on: [self-hosted, linux, x64]

    steps:
        - name: Install clang 14
          run: |
            sudo apt remove -y *clang* 
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 14
            sudo apt install -y clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang

        - name: Install gcc dependencies
          run: sudo apt install -y gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu

        - name: Test clang
          run: clang --version
            