name: Kernel Build
run-name: Kernel Build caused by ${{github.event_name}} - ${{github.actor}} 

on: [push]

jobs:
  KernelBuild:
    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        DEFCONFIG: [exynos9810-crownlte_defconfig, exynos9810-starlte_defconfig, exynos9810-star2lte_defconfig]

    steps:
        - name: Install clang 14
          run: |
            # Remove any preinstaled clang versions
            sudo apt remove -y *clang* 
            sudo apt autoremove -y

            # Install our clang version
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 14
            sudo apt install -y llvm-14 clang-14

            # Link llvm 14 to the defaults
            sudo ln -sf /usr/bin/clang-14 /usr/bin/clang
            sudo ln -sf /usr/bin/ld.lld-14 /usr/bin/ld.lld
            export PATH=/usr/bin/:$PATH

        - name: Install gcc dependencies
          run: sudo apt install -y gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu

        - name: Check out kernel source
          uses: actions/checkout@v4

        - name: Build
          env:
            DEFCONFIG: ${{ matrix.DEFCONFIG }}
          run: |
            ls
            clang --version
            
            make ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32="arm-linux-gnueabi-" O=out "-j$(nproc)" $DEFCONFIG  2>&1 | tee release_out/log_make.txt
            make ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32="arm-linux-gnueabi-" O=out "-j$(nproc)"             2>&1 | tee release_out/log_make.txt
            ls