name: Kernel Build
run-name: Kernel Build caused by ${{github.event_name}} - ${{github.actor}} 

on: [push]

jobs:
  KernelBuild:
    runs-on: [self-hosted, linux, x64]

    steps:
        - name: Install clang 14
          run: |
            sudo apt remove -y *clang* 
            sudo apt autoremove -y

            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 14
            sudo apt install -y llvm-14 clang-14

        - name: Install gcc dependencies
          run: sudo apt install -y gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu

        - name: Test clang
          run: |
            clang --version
            whereis clang
      