name: Kernel Build
run-name: Kernel Build caused by ${{github.event_name}} - ${{github.actor}} 

on: [push]

jobs:
  KernelBuild:
    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        DEFCONFIG: [exynos9810-crownlte_defconfig, exynos9810-starlte_defconfig, exynos9810-star2lte_defconfig]

    steps:
        - name: Install clang 14
          run: |
            # Remove any preinstaled clang versions
            sudo apt remove -y *clang* 
            sudo apt autoremove -y

            # Install our clang version
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 14
            sudo apt install -y llvm-14 clang-14

            # Link llvm 14 to the defaults
            sudo ln -sf /usr/bin/clang-14 /usr/bin/clang
            sudo ln -sf /usr/bin/ld.lld-14 /usr/bin/ld.lld
            export PATH=/usr/bin/:$PATH

        - name: Install gcc dependencies
          run: sudo apt install -y gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu

        - name: Build
          env:
            DEFCONFIG: ${{ matrix.DEFCONFIG }}
          run: |
            export ARCH=arm64 
            export CC=clang
            export LD=ld.lld
            export LLVM=1
            export LLVM_IAS=1
            export CLANG_TRIPLE=aarch64-linux-gnu-
            export CROSS_COMPILE=aarch64-linux-gnu-
            export CROSS_COMPILE_ARM32="arm-linux-gnueabi-"

            clang --version
            
            make O=out "-j$(nproc)" $DEFCONFIG  2>&1 | tee release_out/log_make.txt
            make O=out "-j$(nproc)" 2>&1 | tee release_out/log_make.txt
        